name: tgstickers
description: Use Telegram tickers anywhere

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  window_manager: ^0.3.8
  path_provider: ^2.0.11
  fluentui_icons: ^1.0.0
  super_clipboard: ^0.8.12
  blur: ^3.1.0
  path: ^1.8.2
  http: ^1.2.1
  image: ^4.1.7
  file_picker: ^8.0.3
  dart_emoji: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any


flutter:
  uses-material-design: true